import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/StartPage.module.css'
import Image from 'next/image'
import logo from '@/image/spotifyLogo.png'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const clientId = '5c03a2d9ca984c8dbc56aa9c2fbf05c6'
  const redirect = 'http://localhost:3000/auth'

  const authUrl = `https://accounts.spotify.com/authorize?client_id=${clientId}&response_type=code&redirect_uri=${redirect}`

  return (
    <>
      <Head>
        <title>Spotify Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={styles.first_main}>
        <Image className={styles.first_logo} src={logo} alt="spotify logo" />
        <h3 className={styles.first_title}>
          Connect to the application and start enjoying.
        </h3>
        <a href={authUrl} className={styles.first_btn} data-testid="connect">
          {' '}
          Connect
        </a>
      </div>
    </>
  )
}
